zesarux: fix build for libcaca-0.99.beta20
Without the change `zesarux` fails build on `master` as:

    scrcaca.c:51:5: error: unknown type name 'cucul_canvas_t'; did you mean 'caca_canvas_t'?
       51 |     cucul_canvas_t *cv; caca_display_t *dp; caca_event_t ev;
          |     ^~~~~~~~~~~~~~
          |     caca_canvas_t

(cherry picked from commit 77a8b9fa82a45bbf48978aaa095ce72b8ff5e0a9)